"Choices for the admin site"

states = (
('AL','Alabama'),
('AK','Alaska'),
('AZ','Arizona'),
('AR','Arkansas'),
('CA','California'),
('CO','Colorado'),
('CT','Connecticut'),
('DE','Delaware'),
('DC','District of Columbia'),
('FL','Florida'),
('GA','Georgia'),
('HI','Hawaii'),
('ID','Idaho'),
('IL','Illinois'),
('IN','Indiana'),
('IA','Iowa'),
('KS','Kansas'),
('KY','Kentucky'),
('LA','Louisiana'),
('ME','Maine'),
('MT','Montana'),
('NE','Nebraska'),
('NV','Nevada'),
('NH','New Hampshire'),
('NJ','New Jersey'),
('NM','New Mexico'),
('NY','New York'),
('NC','North Carolina'),
('ND','North Dakota'),
('OH','Ohio'),
('OK','Oklahoma'),
('OR','Oregon'),
('MD','Maryland'),
('MA','Massachusetts'),
('MI','Michigan'),
('MN','Minnesota'),
('MS','Mississippi'),
('MO','Missouri'),
('PA','Pennsylvania'),
('RI','Rhode Island'),
('SC','South Carolina'),
('SD','South Dakota'),
('TN','Tennessee'),
('TX','Texas'),
('UT','Utah'),
('VT','Vermont'),
('VA','Virginia'),
('WA','Washington'),
('WV','West Virginia'),
('WI','Wisconsin'),
('WY','Wyoming'),
)

os = (
('Windows ME','Windows ME'),
('Windows 98/95','Windows 98/95'),
('Windows Embedded', 'Windows Embedded'),
('Windows 2000','Windows 2000'),
('Windows XP','Windows XP'),
('Windows Vista','Windows Vista'),
('Windows 7','Windows 7'),
('Windows 8','Windows 8'),
('Other', 'Other'),
)

pos = [
('Maitre D','Maitre D'),
('Pixel Point','Pixel Point'),
('Comtrex','Comtrex'),
('Camaleon', 'Camaleon'),
('Reflection', 'Reflection'),
('Other', 'Other'),
]

